title: S Jahnvai Srividya # your name (or website title) here
logo: "/images/Screenshot from 2019-10-12 12-40-01.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <center><b>Co-founder & CDO - Clappr.</b></center><br>
  A final year Computer Science and Engineering student, an aspiring Data-Scientist, a vivid Hackathon aficionado.
  <br><br>
  I am someone who loves research and enjoys every second being buried in data. I am very keen on developig my skills to make sure everything i ever produce will be the best of its time. 
  <br><br>
  <a href="https://www.linkedin.com/in/jahnavi-srividya/">View My LinkedIn Profile</a> 
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here


