title: S Jahnvai Srividya # your name (or website title) here
logo: "/images/Screenshot from 2019-10-12 12-40-01.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <center><b>President of Association of Computer Engineers | Chairperson ACM-W student Chapter<br>SSN College of Engineering</b></center><br>
  A final year Computer Science and Engineering student, an aspiring Data-Scientist, a vivid Hackathon aficionado.
  <br><br>
  I am a woman who loves research and enjoys every second being buried in data. I am very keen on developing my skills to make sure everything I ever produce will be the best of its time. I am great at ideation and problem solving, having participated in over 10 hackathons and coming up with top ideas I want to start my own company one day and convert my research into a real world product.
  <br><br>
  <a href="https://www.linkedin.com/in/jahnavi-srividya/">View My LinkedIn Profile</a> 
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
future: true

