title: S Jahnvai Srividya # your name (or website title) here
logo: "/images/jahnavisrividyas.jpeg?raw=true" # your photo (or logo) here
description:
  > # your text below (remove <br> elements if you don't need line breaks)
  <center><b>President of Association of Computer Engineers | Chairperson ACM-W student Chapter<br>SSN College of Engineering</b></center><br>
  A final year Computer Science and Engineering student, an aspiring Data-Scientist, a vivid Hackathon aficionado.
  <br>
  <br>
  <a href="https://www.linkedin.com/in/jahnavi-srividya/">View My LinkedIn Profile</a>
  <br>
  <a href="/pdf/SJahnaviSrividya-Resume.pdf" target="blank">My Resume</a>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
future: true
