title: S Jahnvai Srividya # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A Final year ComputerScience and Engineering student, who aspires to be a Data-Scientist.
  <br><br>
  I am someone who loves research and enjoys every second being buried in data. I am very keen on developig my skills to make sure everything i ever produce will be the best of its time. 
  <br><br>
  <a href="https://www.linkedin.com/in/jahnavi-srividya/">View My LinkedIn Profile</a> 
  

